# Generated by Django 4.1.2 on 2022-10-15 06:28

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_post_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default="unslug", editable=False, populate_from="name"
            ),
            preserve_default=False,
        ),
    ]
