# Generated by Django 4.1.2 on 2022-10-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_post_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="snippet",
            field=models.CharField(
                default="Click Link Above To Read Post...", max_length=255
            ),
        ),
    ]
