# Generated by Django 4.1.2 on 2022-10-16 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="ava",
            field=models.ImageField(blank=True, null=True, upload_to="images/profile"),
        ),
        migrations.AddField(
            model_name="profile",
            name="facebook_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="instagram_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="twitter",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="web_site_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
