# Generated by Django 4.1.2 on 2022-10-16 18:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="prev_comment",
        ),
        migrations.AddField(
            model_name="comment",
            name="time_create",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comment",
            name="time_update",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
