# Generated by Django 4.1.2 on 2022-10-18 06:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_alter_comment_options_alter_post_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ("-time_create",)},
        ),
        migrations.RemoveField(
            model_name="comment",
            name="published",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="time",
        ),
        migrations.AddField(
            model_name="comment",
            name="time_create",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comment",
            name="time_update",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="time_update",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
