# Generated by Django 4.1.2 on 2022-10-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_alter_comment_options_remove_comment_published_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="followers",
            field=models.ManyToManyField(blank=True, null=True, to="main.profile"),
        ),
    ]
